Update embeddings.md
Without "api_version" will raise an error like this: "MyProjectPath/openai/api_resources/abstract/engine_api_resource.py", line 37, in class_url
    raise error.InvalidRequestError(
TypeError: __init__() missing 1 required positional argument: 'param'

Corresponding code:
            if not api_version:
                raise error.InvalidRequestError(
                    "An API version is required for the Azure API type."
                )

Please take a look ~